### ISSUE TITLE
Is the voc_2012_trainaug.json and voc_2012_val.json files obtained by converting the voc's xml annotations to json format?

### ISSUE THREAD

**Issue by YangYi-hub** [ZechengLi19/CIM#1]
The VOC2012 dataset doesn't provide json annotation files, so I'm wondering if the json files needed in the model are generated additionally? If so is it possible to provide the corresponding generated files?

**Comment by ZechengLi19** [comment]
Thanks for your attention. 

I have placed the json files in this link, please feel free to use it. [Link](https://drive.google.com/drive/folders/1CrzR3V5dgrwzaQYER5AwnLD_OfpjUylh?usp=sharing)

**Comment by YangYi-hub** [comment]
Thanks a lot .

**Comment by ZechengLi19** [comment]
🎉Feel free to reopen if you meet some questions~

**Comment by YangYi-hub** [comment]
Hi, I'm having another problem during training. There is a new issue in training about the number of elements in the output of the model with the following error message. 
  4%|███▉                                                                                      | 1940/45000 [14:02<5:01:53,  2.38it/s][Dec26-18-30-01_serverA_step][resnet50_voc.yaml][Step 1941 / 45000]
                loss: 1.431148, lr: 0.000250 time: 0.434069, eta: 5:11:31
                bag_loss: 0.257181, pcl_loss: 0.739873, cls_loss: 0.191624, iou_loss: 0.127284
  4%|███▉                                                                                      | 1941/45000 [14:03<5:11:52,  2.30it/s]
Traceback (most recent call last):
  File "./tools/train.py", line 464, in <module>
    main()
  File "./tools/train.py", line 432, in main
    net_outputs = model(**input_data)
  File "/home/～/tools/miniconda3/envs/cim/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/～/CIM-main/lib/nn/parallel/data_parallel.py", line 108, in forward
    outputs = [self.module(*inputs[0], **kwargs[0])]
  File "/home/～/tools/miniconda3/envs/cim/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/～/CIM-main/lib/modeling/model_builder.py", line 187, in forward
    using_CIM=self.using_CIM[i])
ValueError: too many values to unpack (expected 3)

I have built the environment by following the INSTALL.md. My torch, cuda, and python versions are as follows:
torch：1.10.0+cu111
cuda：11.1
python：3.6.13
Looking forward to your answer.

**Comment by ZechengLi19** [comment]
> Hi, I'm having another problem during training. There is a new issue in training about the number of elements in the output of the model with the following error message. 4%|███▉ | 1940/45000 [14:02<5:01:53, 2.38it/s][Dec26-18-30-01_serverA_step][resnet50_voc.yaml][Step 1941 / 45000] loss: 1.431148, lr: 0.000250 time: 0.434069, eta: 5:11:31 bag_loss: 0.257181, pcl_loss: 0.739873, cls_loss: 0.191624, iou_loss: 0.127284 4%|███▉ | 1941/45000 [14:03<5:11:52, 2.30it/s] Traceback (most recent call last): File "./tools/train.py", line 464, in main() File "./tools/train.py", line 432, in main net_outputs = model(**input_data) File "/home/～/tools/miniconda3/envs/cim/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/～/CIM-main/lib/nn/parallel/data_parallel.py", line 108, in forward outputs = [self.module(*inputs[0], **kwargs[0])] File "/home/～/tools/miniconda3/envs/cim/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/～/CIM-main/lib/modeling/model_builder.py", line 187, in forward using_CIM=self.using_CIM[i]) ValueError: too many values to unpack (expected 3)
> 
> I have built the environment by following the INSTALL.md. My torch, cuda, and python versions are as follows: torch：1.10.0+cu111 cuda：11.1 python：3.6.13 Looking forward to your answer.

My bad. It seems like a mistake I made when cleaning up my code? You can fix it quickly, just change this line of code. [Link](https://github.com/ZechengLi19/CIM/blob/33f695de12a04e3a9da434bccf21824d20a6ee7d/lib/modeling/heads.py#L430)

**Comment by YangYi-hub** [comment]
> > Hi, I'm having another problem during training. There is a new issue in training about the number of elements in the output of the model with the following error message. 4%|███▉ | 1940/45000 [14:02<5:01:53, 2.38it/s][Dec26-18-30-01_serverA_step][resnet50_voc.yaml][Step 1941 / 45000] loss: 1.431148, lr: 0.000250 time: 0.434069, eta: 5:11:31 bag_loss: 0.257181, pcl_loss: 0.739873, cls_loss: 0.191624, iou_loss: 0.127284 4%|███▉ | 1941/45000 [14:03<5:11:52, 2.30it/s] Traceback (most recent call last): File "./tools/train.py", line 464, in main() File "./tools/train.py", line 432, in main net_outputs = model(**input_data) File "/home/～/tools/miniconda3/envs/cim/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/～/CIM-main/lib/nn/parallel/data_parallel.py", line 108, in forward outputs = [self.module(*inputs[0], **kwargs[0])] File "/home/～/tools/miniconda3/envs/cim/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/～/CIM-main/lib/modeling/model_builder.py", line 187, in forward using_CIM=self.using_CIM[i]) ValueError: too many values to unpack (expected 3)
> > I have built the environment by following the INSTALL.md. My torch, cuda, and python versions are as follows: torch：1.10.0+cu111 cuda：11.1 python：3.6.13 Looking forward to your answer.
> 
> My bad. It seems like a mistake I made when cleaning up my code? You can fix it quickly, just change this line of code. [Link](https://github.com/ZechengLi19/CIM/blob/33f695de12a04e3a9da434bccf21824d20a6ee7d/lib/modeling/heads.py#L430)

Thank you for replying so quickly.

**Comment by YangYi-hub** [comment]
Hi, I got the contents of the Dec26-23-17-22_serverA_step folder after I finished training. The folder address for testing is Mar22-00-46-22_user-Super-Server_step and the test requires Mar22-00-46-22_user-Super-Server_step/ckpt/model_step44999.pth to exist, so I'm putting Dec26 -23-17-22_serverA_step folder to get the model weights to Mar22-00-46-22_user-Super-Server_step.
Now the prompt needs the file Mar22-00-46-22_user-Super-Server_step/test/model_step44999/detections.pkl. Can you tell me which file the detections.pkl file corresponds to in the output or how to get this file. Below is the error message:
INFO evaluation.py: 143: Called with args:
INFO evaluation.py: 144: Namespace(cfg_file='./configs/resnet50_voc.yaml', dataset='voc2012sbdval', output_dir=None, result_path='./Outputs/resnet50_voc/Mar22-00-46-22_user-Super-Server_step/test/model_step44999/detections.pkl', set_cfgs=[], total_process=24)
args.result_path: ./Outputs/resnet50_voc/Mar22-00-46-22_user-Super-Server_step/test/model_step44999/detections.pkl
Traceback (most recent call last):
  File "tools/evaluation.py", line 147, in <module>
    assert os.path.exists(args.result_path), 'result_path doesnot exit'
AssertionError: result_path doesnot exit

**Comment by ZechengLi19** [comment]
> the prompt needs the file Mar22-00-46-22_user-Super-Server_step/test/model_step44999/detections.pkl. Can you tell me which file the detections.pkl file corresponds to in the output or how to get this file. Below is the error message:
> INFO evaluation.py: 143: Called with args:
> INFO evaluation.py: 144: Namespace(cfg_file='./configs/resnet50_voc.yaml', dataset='voc2012sbdval', output_dir=None, result_path='./Outputs/resnet50_voc/Mar22-00-46-22_user-Super-Server_step/test/model_step44999/

You need to update these four values `cfg_file, output_file, dataset, iter_time` according to your needs. This is the rule for all bash files. https://github.com/ZechengLi19/CIM/blob/33f695de12a04e3a9da434bccf21824d20a6ee7d/scripts/eval_CIM.sh#L1-L5

In your case, you need to change .bash file as
```
# Editable
cfg_file=./configs/resnet50_voc.yaml
output_file=./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step
dataset=voc2012sbdval
iter_time=model_step44999
```

Maybe there are still some problems with the above changes, because I don’t know your file structure, so you’d better write `output_file` as an absolute path.

**Comment by YangYi-hub** [comment]
Thanks, I've changed the output_file path of the .bash file, but I'm still not sure about . /Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/test/model_step44999/detections.pkl file where it comes from, it is this path result_pkl=${output_file}/test/$ {iter_time}/detections.pkl corresponding to detections.pkl.
Here is the full error message:
loading annotations into memory...                                                                                                    
Done (t=0.02s)                                                                                                                        
creating index...                                                                                                                     
index created!                                                                                                                        
INFO json_dataset.py:  71: /home/～/CIM-main/data/VOC2012/annotations/voc_2012_val.json                            
INFO subprocess.py:  87: detection range command 0: python /home/～/CIM-main/tools/test_net.py --range 0 725 --cfg 
./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/test/model_step44999/detection_range_config.yaml --set TEST.DATASETS '("voc_2012_sb
dval",)' TEST.PROPOSAL_FILES '("./data/cob/voc_2012_val.pkl",)' --output_dir ./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/test/m
odel_step44999 --load_ckpt ./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/ckpt/model_step44999.pth                                
INFO subprocess.py:  87: detection range command 1: python /home/～/CIM-main/tools/test_net.py --range 725 1449 --c
fg ./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/test/model_step44999/detection_range_config.yaml --set TEST.DATASETS '("voc_2012
_sbdval",)' TEST.PROPOSAL_FILES '("./data/cob/voc_2012_val.pkl",)' --output_dir ./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/tes
t/model_step44999 --load_ckpt ./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/ckpt/model_step44999.pth                             
INFO subprocess.py: 127: # ---------------------------------------------------------------------------- #                             
INFO subprocess.py: 129: stdout of subprocess 0 with range [1, 725]                                                                   
INFO subprocess.py: 131: # ---------------------------------------------------------------------------- #                             
INFO test_net.py:  93: Called with args:                                                                                              
INFO test_net.py:  94: Namespace(cfg_file='./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/test/model_step44999/detection_range_con
fig.yaml', dataset='', load_ckpt='./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/ckpt/model_step44999.pth', load_detectron=None, m
ulti_gpu_testing=False, output_dir='./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/test/model_step44999', range=[0, 725], set_cfgs
=['TEST.DATASETS', '("voc_2012_sbdval",)', 'TEST.PROPOSAL_FILES', '("./data/cob/voc_2012_val.pkl",)'], vis=False)                     
single GPU                                                                                                                            
Traceback (most recent call last):                                                                                                    
  File "/home/～/CIM-main/tools/test_net.py", line 123, in <module>                                                
    merge_cfg_from_file(args.cfg_file)                                                                                                
  File "/home/～/CIM-main/lib/core/config.py", line 678, in merge_cfg_from_file                                    
    yaml_cfg = AttrDict(yaml.safe_load(f))#.load(f))                                                                                  
  File "/home/～/tools/miniconda3/envs/cim/lib/python3.6/site-packages/yaml/__init__.py", line 125, in safe_load             
    return load(stream, SafeLoader)
  File "/home/～/tools/miniconda3/envs/cim/lib/python3.6/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/～/tools/miniconda3/envs/cim/lib/python3.6/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/～/tools/miniconda3/envs/cim/lib/python3.6/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/home/～/tools/miniconda3/envs/cim/lib/python3.6/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/home/～/tools/miniconda3/envs/cim/lib/python3.6/site-packages/yaml/constructor.py", line 429, in construct_undefined node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/new:utils.collections.AttrDict'
  in "./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/test/model_step44999/detection_range_config.yaml", line 1, column 1
Traceback (most recent call last):
  File "tools/test_net.py", line 169, in <module>
    check_expected_results=True,flag=cfg.transform_mode)
  File "/home/～/CIM-main/lib/core/test_engine.py", line 142, in run_inference
    all_results = result_getter()
  File "/home/～/CIM-main/lib/core/test_engine.py", line 119, in result_getter
    multi_gpu=multi_gpu_testing,flag=flag
  File "/home/～/CIM-main/lib/core/test_engine.py", line 169, in test_net_on_dataset
    args, dataset_name, proposal_file, num_images, output_dir
  File "/home/～/CIM-main/lib/core/test_engine.py", line 223, in multi_gpu_test_net_on_dataset
    args.load_ckpt, args.load_detectron, opts
  File "/home/～/CIM-main/lib/utils/subprocess.py", line 107, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/home/～/CIM-main/lib/utils/subprocess.py", line 145, in log_subprocess_output
    assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: 1)
INFO evaluation.py: 143: Called with args:
INFO evaluation.py: 144: Namespace(cfg_file='./configs/resnet50_voc.yaml', dataset='voc2012sbdval', output_dir=None, result_path='./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/test/model_step44999/detections.pkl', set_cfgs=[], total_process=24)
args.result_path: ./Outputs/resnet50_voc/Dec26-23-17-22_serverA_step/test/model_step44999/detections.pkl
Traceback (most recent call last):
  File "tools/evaluation.py", line 147, in <module>
    assert os.path.exists(args.result_path), 'result_path doesnot exit'
AssertionError: result_path doesnot exit

**Comment by ZechengLi19** [comment]
detections.pkl is generated by https://github.com/ZechengLi19/CIM/blob/33f695de12a04e3a9da434bccf21824d20a6ee7d/scripts/eval_CIM.sh#L12-L16

Please check version of PyYAML, because I found this error occur 
`yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/new:utils.collections.AttrDict'`
