### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by geek-APTX4869** [ZechengLi19/CIM#2]
No module named 'utils.cython_bbox'.

**Comment by ZechengLi19** [comment]
> No module named 'utils.cython_bbox'.

Please tell me the complete error message and the command you run.

**Comment by ZechengLi19** [comment]
> No module named 'utils.cython_bbox'.

I have compiled this repository in `python3.6`. Could you check the python version you are using? If it does not match, it may cause this error. Therefore, you need to compile your python. Refer to the following operations.
```
cd ./lib
python setup.py build_ext --inplace
```

Please let me know if the above operation works and I will remind everyone in subsequent updates.

**Comment by geek-APTX4869** [comment]
> > No module named 'utils.cython_bbox'.
> 
> I have compiled this repository in `python3.6`. Could you check the python version you are using? If it does not match, it may cause this error. Therefore, you need to compile your python. Refer to the following operations.
> 
> ```
> cd ./lib
> python setup.py build_ext --inplace
> ```
> 
> Please let me know if the above operation works and I will remind everyone in subsequent updates.

Happy New Year!😊 With the operations you recommend, `python3.11` works. New problem is 'data/VOC2012/annotations/voc_2012_trainaug.json' not found

**Comment by ZechengLi19** [comment]
Happy New Year🎉

Thanks for your feedback. I will update the readme in the near future.

If you have any questions, please feel free to reopen this issue.
