### ISSUE TITLE
About runtime.

### ISSUE THREAD

**Issue by Colezwhy** [ZechengLi19/CIM#3]
Hi, thank you for your great work.
How long will it take to run the whole pipeline?(with MaskRCNN refinement and without)

**Comment by ZechengLi19** [comment]
> Hi, thank you for your great work. How long will it take to run the whole pipeline?(with MaskRCNN refinement and without)

The running time of pipeline without MaskRCNN is shown in the figure. (one RTX 3090 GPU)
<img width="303" alt="image" src="https://github.com/ZechengLi19/CIM/assets/59078823/059aab33-c33c-4855-8bdd-eb336cd136fd">

The running time of MaskRCNN on the VOC dataset is one hour. The running time of MaskRCNN on the COCO dataset is 22 hours. (two RTX 3090 GPUs, if I remember correctly)

**Comment by Colezwhy** [comment]
> > Hi, thank you for your great work. How long will it take to run the whole pipeline?(with MaskRCNN refinement and without)
> 
> The running time of pipeline without MaskRCNN is shown in the figure. (one RTX 3090 GPU) <img alt="image" width="303" src="https://private-user-images.githubusercontent.com/59078823/316240539-059aab33-c33c-4855-8bdd-eb336cd136fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExOTg3NTksIm5iZiI6MTcxMTE5ODQ1OSwicGF0aCI6Ii81OTA3ODgyMy8zMTYyNDA1MzktMDU5YWFiMzMtYzMzYy00ODU1LThiZGQtZWIzMzZjZDEzNmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDEyNTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NzlmZjMxNmU4MzEwM2YyZWFmMzNmZTk2MDQ3YzRhMTUyZGIxN2Y3OTlkNDdlODQ1MDg1OGE2NWRhZjQzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QuJvOPSovnqd3EShRYj2sI0alkvDrxGztn52dRZ-aPc">
> 
> The running time of MaskRCNN on the VOC dataset is one hour. The running time of MaskRCNN on the COCO dataset is 22 hours. (two RTX 3090 GPUs, if I remember correctly)

Sorry for missing that, thank you very much. I will close it.
