### ISSUE TITLE
Maskrcnn refinement

### ISSUE THREAD

**Issue by YangYi-hub** [ZechengLi19/CIM#4]
HELLO! Can you tell me how to set up maskrcnn for refinement? Do I need to additionally modify the model to provide labels for each image when maskrcnn validates?

**Comment by ZechengLi19** [comment]
> HELLO! Can you tell me how to set up maskrcnn for refinement? Do I need to additionally modify the model to provide labels for each image when maskrcnn validates?

Hi, we just run `bash ./scripts/generate_msrcnn_label.sh` to generate coco-format pseudo labels. Then, we leverage 
 mmdetection to set up maskrcnn. You can get our maskrcnn config files from [here](https://drive.google.com/drive/folders/11DrIJmIy7j7rIrUlvGNLJKFUnKbUjdWc).

**Comment by YangYi-hub** [comment]
Thank you! But currently the latest version of mmdetection has some config settings that are no longer compatible with the version you provided, is it possible to provide a repository of the mmdetection code for the maskrcnn you are using?

**Comment by ZechengLi19** [comment]
> Thank you! But currently the latest version of mmdetection has some config settings that are no longer compatible with the version you provided, is it possible to provide a repository of the mmdetection code for the maskrcnn you are using?

It may be `version 1.x`, but the new version of mmdetection can definitely be used. All you need to do is replace the real `train.json` label file with the generated `train.json` file.

**Comment by YangYi-hub** [comment]
Thanks! But there are some settings that keep reporting errors. For example, 'albu' reports the error 'IndexError: index 0 is out of bounds for axis 0 with size 0'. So can you provide your version of mmdetection project?
