### ISSUE TITLE
Center_points谷歌云盘文件失效

### ISSUE THREAD

**Issue by HIM** [ZechengLi19/CIM#5]
作者您好，VOC2012/Center_points/的谷歌云盘文件失效了，您可以更新一下文件链接吗，麻烦您了

**Comment by ZechengLi19** [comment]
> 作者您好，VOC2012/Center_points/的谷歌云盘文件失效了，您可以更新一下文件链接吗，麻烦您了

You can download from here [[download]](https://github.com/clovaai/BESTIE/releases/download/asset/Center_points.zip)

**Comment by HIM** [comment]
谢谢！
